export var formI = [
  {
    symbol: '-',
    title: 'Bible',
    daysPerWeek: 5,
    duration: 15,
    teacherInvolvement: 3,
  },
  {
    symbol: '-',
    title: 'Practice Instrument',
    daysPerWeek: 5,
    duration: 15,
    teacherInvolvement: 3,
    custom: true,
  },
  {
    symbol: '@',
    title: 'Reading',
    daysPerWeek: 5,
    duration: 10,
    teacherInvolvement: 3,
  },
  {
    symbol: '@',
    title: 'Copywork',
    daysPerWeek: 5,
    duration: 10,
    teacherInvolvement: 2,
  },
  {
    symbol: '',
    title: 'Recitation',
    daysPerWeek: 3,
    duration: 10,
    teacherInvolvement: 3,
  },
  {
    symbol: '',
    title: 'Geography',
    daysPerWeek: 2,
    duration: 15,
    teacherInvolvement: 3,
  },
  {
    symbol: '-',
    title: 'Natural History',
    daysPerWeek: 3,
    duration: 10,
    teacherInvolvement: 3,
  },
  {
    symbol: '',
    title: 'Geography',
    daysPerWeek: 2,
    duration: 15,
    teacherInvolvement: 3,
  },
  {
    symbol: '@',
    title: 'Drawing',
    daysPerWeek: 2,
    duration: 20,
    teacherInvolvement: 2,
  },
  {
    symbol: '-',
    title: 'Literature Tales',
    daysPerWeek: 2,
    duration: 20,
    teacherInvolvement: 3,
  },
  {
    symbol: '-',
    title: 'American History',
    daysPerWeek: 2,
    duration: 20,
    teacherInvolvement: 3,
  },
  {
    symbol: '',
    title: 'Modern Language 1',
    daysPerWeek: 3,
    duration: 10,
    teacherInvolvement: 3,
  },
  {
    symbol: '@',
    title: 'Art Appreciation',
    daysPerWeek: 1,
    duration: 10,
    teacherInvolvement: 3,
  },
  {
    symbol: '',
    title: 'Singing',
    daysPerWeek: 4,
    duration: 10,
    teacherInvolvement: 2,
  },
  {
    symbol: '',
    title: 'Play/Drill/Phys. Ed.',
    daysPerWeek: 5,
    duration: 15,
    teacherInvolvement: 1,
  },
  {
    symbol: '',
    title: 'Math',
    daysPerWeek: 5,
    duration: 20,
    teacherInvolvement: 2,
  },
  {
    symbol: '',
    title: 'Handicraft/Work',
    daysPerWeek: 5,
    duration: 20,
    teacherInvolvement: 2,
  },
  {
    symbol: '',
    title: 'Music Appreciation',
    daysPerWeek: 1,
    duration: 10,
    teacherInvolvement: 2,
  }
];

export var formIIA = [
	{
		symbol: '',
		title: 'Music Appreciation',
		daysPerWeek: 1,
		duration: 10,
		teacherInvolvement: 2,
	},
	{
		symbol: '@',
		title: 'Dictation',
		daysPerWeek: 1,
		duration: 10,
		teacherInvolvement: 2,
	},
	{
		symbol: '',
		title: 'Singing',
		daysPerWeek: 3,
		duration: 10,
		teacherInvolvement: 1,
	},
	{
		symbol: '',
		title: 'Recitation',
		daysPerWeek: 5,
		duration: 10,
		teacherInvolvement: 1,
	},
	{
		symbol: '+',
		title: 'Latin',
		daysPerWeek: 2,
		duration: 30,
		teacherInvolvement: 2,
	},
	{
		symbol: '-',
		title: 'British History',
		daysPerWeek: 1,
		duration: 20,
		teacherInvolvement: 1,
	},
	{
		symbol: '-',
		title: 'Bible',
		daysPerWeek: 5,
		duration: 15,
		teacherInvolvement: 3,
	},
	{
		symbol: '',
		title: 'Play',
		daysPerWeek: 5,
		duration: 15,
		teacherInvolvement: 1,
	},
	{
		symbol: '-',
		title: 'Natural History',
		daysPerWeek: 1,
		duration: 30,
		teacherInvolvement: 1,
	},
	{
		symbol: '@',
		title: 'Copywork',
		daysPerWeek: 5,
		duration: 10,
		teacherInvolvement: 1,
	},
	{
		symbol: '+',
		title: 'Grammar',
		daysPerWeek: 2,
		duration: 15,
		teacherInvolvement: 3,
	},
	{
		symbol: '+',
		title: 'Math',
		daysPerWeek: 5,
		duration: 30,
		teacherInvolvement: 2,
	},
	{
		symbol: '',
		title: 'Geography',
		daysPerWeek: 2,
		duration: 20,
		teacherInvolvement: 1,
	},
	{
		symbol: '-',
		title: 'Literature',
		daysPerWeek: 1,
		duration: 30,
		teacherInvolvement: 1,
	},
	{
		symbol: '-',
		title: 'Citizenship',
		daysPerWeek: 1,
		duration: 30,
		teacherInvolvement: 3,
	},
	{
		symbol: '@',
		title: 'Dictation',
		daysPerWeek: 2,
		duration: 20,
		teacherInvolvement: 2,
	},
	{
		symbol: '',
		title: 'Modern Language 1',
		daysPerWeek: 3,
		duration: 20,
		teacherInvolvement: 3,
	},
	{
		symbol: '-',
		title: 'Ancient History',
		daysPerWeek: 1,
		duration: 30,
		teacherInvolvement: 1,
	},
	{
		symbol: '-',
		title: 'Natural History',
		daysPerWeek: 2,
		duration: 20,
		teacherInvolvement: 1,
	},
	{
		symbol: '-',
		title: 'American History',
		daysPerWeek: 1,
		duration: 30,
		teacherInvolvement: 1,
	}
];

export var formIII = [{
    symbol: '-',
    title: 'Bible',
    daysPerWeek: 5,
    duration: 15,
    teacherInvolvement: 1,
  },
  {
    symbol: '',
    title: 'Singing',
    daysPerWeek: 3,
    duration: 10,
    teacherInvolvement: 1,
  },
  {
    symbol: '',
    title: 'Recitation',
    daysPerWeek: 5,
    duration: 10,
    teacherInvolvement: 1,
  },
  {
    symbol: '',
    title: 'Music Appreciation',
    daysPerWeek: 1,
    duration: 10,
    teacherInvolvement: 2,
  },
  {
    symbol: '@',
    title: 'Art Appreciation',
    daysPerWeek: 1,
    duration: 10,
    teacherInvolvement: 3,
  },
  {
    symbol: '-',
    title: 'British History',
    daysPerWeek: 1,
    duration: 30,
    teacherInvolvement: 1,
  },
  {
    symbol: '+',
    title: 'Latin',
    daysPerWeek: 2,
    duration: 30,
    teacherInvolvement: 1,
  },
  {
    symbol: '',
    title: 'Composition',
    daysPerWeek: 1,
    duration: 30,
    teacherInvolvement: 1,
  },
  {
    symbol: '@',
    title: 'Copywork',
    daysPerWeek: 1,
    duration: 10,
    teacherInvolvement: 1,
  },
  {
    symbol: '',
    title: 'Play',
    daysPerWeek: 5,
    duration: 15,
    teacherInvolvement: 1,
  },
  {
    symbol: '+',
    title: 'Math',
    daysPerWeek: 5,
    duration: 30,
    teacherInvolvement: 2,
  },
  {
    symbol: '',
    title: 'Modern Language',
    daysPerWeek: 3,
    duration: 30,
    teacherInvolvement: 2,
  },
  {
    symbol: '-',
    title: 'American History',
    daysPerWeek: 1,
    duration: 30,
    teacherInvolvement: 1,
  },
  {
    symbol: '-',
    title: 'Ancient History',
    daysPerWeek: 1,
    duration: 30,
    teacherInvolvement: 1,
  },
  {
    symbol: '',
    title: 'Geography',
    daysPerWeek: 1,
    duration: 30,
    teacherInvolvement: 1,
  },
  {
    symbol: '-',
    title: 'Natural History',
    daysPerWeek: 3,
    duration: 40,
    teacherInvolvement: 1,
  },
  {
    symbol: '-',
    title: 'Citizenship',
    daysPerWeek: 1,
    duration: 30,
    teacherInvolvement: 3,
  },
  {
    symbol: '',
    title: 'Geography',
    daysPerWeek: 1,
    duration: 20,
    teacherInvolvement: 1,
  },
  {
    symbol: '+',
    title: 'Grammar',
    daysPerWeek: 2,
    duration: 30,
    teacherInvolvement: 3,
  },
  {
    symbol: '@',
    title: 'Dictation',
    daysPerWeek: 2,
    duration: 20,
    teacherInvolvement: 2,
  },
  {
    symbol: '-',
    title: 'Natural History',
    daysPerWeek: 1,
    duration: 45,
    teacherInvolvement: 1,
  },
  {
    symbol: '-',
    title: 'Literature',
    daysPerWeek: 1,
    duration: 30,
    teacherInvolvement: 1,
  }
];
